// Relocatable Sappy driver constants

#ifndef SAPPY_GSF_H_INCLUDED
#define SAPPY_GSF_H_INCLUDED

#define SAPPY_GSF_SELECTSONG_OFFSET 0x00E8
#define SAPPY_GSF_MAIN_OFFSET       0x00EC
#define SAPPY_GSF_INIT_OFFSET       0x00F0
#define SAPPY_GSF_VSYNC_OFFSET      0x00F4

#define SAPPY_GSF_MINIGSF_OFFSET    0x0118

#endif /* !SAPPY_GSF_H_INCLUDED */
